#!/bin/bash

if [ $# -eq 0 ]; then
  echo "usage: CMD target_directory"
  exit
fi
TARGET_DIRECTORY=$1
FILES=()
NO_PAIR_FILES=()
NO_PAIR_FILES_COUNT=0
while IFS= read -r -d $'\n'; do
  FILES+=("$REPLY")
done < <(find "${TARGET_DIRECTORY}" -type f -name "*.mov")
for MOV_FILE in "${FILES[@]}"; do
  PHOTO_FILE=${MOV_FILE/mov/heic}
  if ! [ -f "$PHOTO_FILE" ]; then
    PHOTO_FILE=${MOV_FILE/mov/jpeg}
    if ! [ -f "$PHOTO_FILE" ]; then
      PHOTO_FILE=${MOV_FILE/mov/jpg}
      if ! [ -f "$PHOTO_FILE" ]; then
        echo "$MOV_FILE"
        #rm $MOV_FILE
        #NO_PAIR_FILES_COUNT=$((1+$NO_PAIR_FILES_COUNT))
        NO_PAIR_FILES+=("$MOV_FILE")
      fi
    fi
  fi
done
echo Total scanned ${#FILES[@]} files
echo Total mov file that has no paired picture ${#NO_PAIR_FILES[@]} files

if [ "${#NO_PAIR_FILES[@]}" == "0" ]; then
  exit
fi
read -p "Are you sure want to delete ${#NO_PAIR_FILES[@]} files? [Y/n] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  for MOV_FILE in "${NO_PAIR_FILES[@]}"; do
    echo "$MOV_FILE"
    mv "$MOV_FILE" "$MOV_FILE.no_pair"
  done
fi
